services:
  mongodb:
    image: mongo:latest
    container_name: ignite_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - ignite_network

  redis:
    image: redis:latest
    container_name: ignite_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ignite_network

  minio:
    image: minio/minio
    container_name: ignite_minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - ignite_network

networks:
  ignite_network:
    name: ignite_network
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  minio_data:
